name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -f docker/prod.Dockerfile -t tkd

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Docker Tag and Push
        run: |-
          docker tag tkd southamerica-east1-docker.pkg.dev/luanlmd-384622/tkd/tkd:latest
          docker tag tkd southamerica-east1-docker.pkg.dev/luanlmd-384622/tkd/tkd:v${{ github.run_number }}
          docker push southamerica-east1-docker.pkg.dev/luanlmd-384622/tkd/tkd:latest
          docker push southamerica-east1-docker.pkg.dev/luanlmd-384622/tkd/tkd:v${{ github.run_number }}

      - name: Update Cloud Run Service
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          region: us-east1
          service: "tkd"
          image: "southamerica-east1-docker.pkg.dev/luanlmd-384622/tkd/tkd:v${{ github.run_number }}"
